runtime: python38
instance_class: F2

inbound_services:
- warmup

automatic_scaling:
  max_instances: 1
  min_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.8

entrypoint: python treel-dr/app.py

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto